# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'middleagercityparty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'
 

  # Pods for middleagercityparty

  target 'middleagercitypartyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'middleagercitypartyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
